server:
  port: 8761
info:
  easyframe:
    description: EasyFrame-Eureka
    url: https://github.com/easyframe/easyframe-eureka
    build-by: linzhaoming
management:
  security:
    enabled: false

spring:
  application:
    name: easyframe-eureka
  profiles:
    active: dev

# [dev] Environment
---
spring:
  profiles: dev

# [test] Environment
---
spring:
  profiles: test

# [staging] Environment
---
spring:
  profiles: staging

# [prod] Environment
---
spring:
  profiles: prod